baseURL = "https://blog.nms.com.au"
#languageCode = "en-us"
title = "My doc blog"
#themesDir = "../.."
theme = "m10c"
paginate = 5

[params]
  author = "Paul Taylor"
  description = "Documentation for random IT issues."
  [[params.social]]
    name = "github"
    url = "https://github.com/sinistra"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gohugoio"

  [params.style]
    darkestColor = "#aa1414"
    darkColor = "#212121"
    primaryColor = "#ffffff"
    lightColor = "#a2a2a2"
    lightestColor = "#d3d3d3"

